### PR TITLE
 Quick Settings Tiles for faster toggling vpn

### PR DESCRIPTION
**Pull request by yaoxinghuo**
- Original issue: https://github.com/cernekee/ics-openconnect/issues/31
- Moved to: https://github.com/dlenski/ics-openconnect/issues/2

### CODE REVIEW

**Comment by dlenski** [comment]
Thanks! This is pretty great :grin:.

I'm a dyed-in-the-wool command-line guy, so I want to declutter the diff a little bit…

* I'll fix the tab/space mixture in the source files.
* Do you understand why the files in `/app/src/main/res/layout-v26/status.xml` were added? They appear to do nothing at all. I can delete them and rebuild and it makes zero difference in the appearance of the app.

**Comment by yaoxinghuo** [comment]
Hi, the files in layout-v26 fix the problem on my Android 8(v26) device some text hard to see(they are black color), see the attached screenshots. If it is only my case, of source, just delete the directory.
QQ20190604-111530@2x
QQ20190604-112056@2x

**Comment by dlenski** [comment]
Cool. Thanks for clarifying! I don't see this issue, but if other users have it then we can re-add it as a separate PR.

**Comment by yaoxinghuo** [comment]
OK!

**Pull request closed without merging**
